parameters {
    string(name: 'TARGET_IP', defaultValue: '172.31.47.211', description: 'Agent IP')
    choice(name: 'DEPLOY_ENV', choices: ['PROD', 'QA'], description: 'Target Environment')
}
// Then pass ${params.TARGET_IP} to your Ansible extraVars
